name: PanillaX
version: ${version}
main: com.ruinscraft.panilla.bukkit.PanillaPlugin
api-version: 1.21.4
folia-supported: true
authors: [ds58, Tig3r98]
description: Prevent abusive NBT and harmful packets
website: https://github.com/Tig3r98/Panilla
permissions:
  panilla.log.chat:
    description: View warning logs in chat if enabled in the config
    default: op
  panilla.bypass:
    description: Bypass packet checks
    default: op